language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
- stable
sudo: false
script:
- npm test
before_install:
- npm install -g npm@^3.5.2
deploy:
  provider: npm
  email: git_nikku@nixis.de
  on:
    tags: true
    all_branches: true
    repo: nikku/karma-browserify
  api_key:
    secure: ams34LX5sX48oDATRqpNubvZdT70Aax2IAfg0yJ6vUKILwD/ZYAAdoHRZBYCjdEuPg3U3UFMh+1f+cRfQJSfea6wzmPtBrN5KPYp2EJHByL+kjWn+kIoXA0/rUrjt0LzAWt4ziPbqqYD3ieR7vFvnBNCH6wDh5iWBxyRnwvEQoA=
